### ISSUE TITLE
Добавить package

### ISSUE THREAD

**Issue by olegcherr** [Nourepide/CryptocurrencyMonitor#1]
Ты забыл указать пакет в начале файла:
https://github.com/Nourepide/CryptocurrencyMonitor/blob/7cf576b6fdd87a6706dfac5f43323c33e7586369/app/src/main/java/com/nourepide/learning/cryptocurrencymonitor/MainActivity.kt#L1-L3

`package com.nourepide.learning.cryptocurrencymonitor`

Из-за этого у меня не компилировалось. Не знаю как у тебя компилируется...

**Comment by Nourepide** [comment]
Я его уже на GitHub случайно стёр
