### ISSUE TITLE
Перейти на MVVM

### ISSUE THREAD

**Issue by olegcherr** [Nourepide/CryptocurrencyMonitor#14]
Ну что, приложение работает очень даже неплохо. Хорошо выдерживает пересоздание Активити. Не идеально правда... Например, если во время загрузки данных сменить ориентацию экрана, то прогресс-бар больше не отображается, хотя загрузка-то всё ещё продолжается. Причём продолжается она где-то в фоне, в каком-то потоке, который как бы повис в воздухе, и его невозможно ниоткуда контролировать.

Всё это происходит из-за того, что сейчас наш MainActivity - это так называемый God-object. То есть наш Активити ответственен за слишком большое количество задач: он и загружает данные, и обрабатывает их, попутно наполняя модель; и возится с потоками; и обновляет внешний вид. А ещё он полностью пересоздаётся при смене ориентации. Жуть в общем))

Пора разделять данные и представление :)

В общем надо сделать так, чтобы ViewModel была ответственна за загрузку, преобразование и хранение данных.
А MainActivity должна лишь изменять свой View в соответствии с моделью.

Тебе тут как раз пригодится LiveData.

Итак, наша цель - выполнить следующие требования:
- Активити должен быть ответственен лишь за отображение данных. Он должен представлять из себя максимально тупой View.
- View (Активити) должен быть полностью реактивным. Он должен сам реагировать на изменения в данных.
- Соответственно ViewModel **не** должен выполнять никаких императивных действий с View. Он **не** должен иметь ссылку на View, и **не** должен вызывать у него какие-то методы.
- Таким образом, ViewModel должен хранить данные в виде observable-полей, на изменения которых может подписаться View.

Если будут вопросы - пиши. Подскажу чё почём :)

**Comment by Nourepide** [comment]
Принято
