### ISSUE TITLE
Добавить ProgressBar

### ISSUE THREAD

**Issue by olegcherr** [Nourepide/CryptocurrencyMonitor#2]
https://github.com/Nourepide/CryptocurrencyMonitor/blob/7cf576b6fdd87a6706dfac5f43323c33e7586369/app/src/main/java/com/nourepide/learning/cryptocurrencymonitor/MainActivity.kt#L22

Тут ты выполняешь блокирующую функцию `get()` в главном потоке (aka Main Thread или UI Thread). Так делать нельзя, т.к. у тебя блокируется весь UI.

Все блокирующие вещи нужно выполнять в фоновом потоке. А обновление UI можно делать только из главного потока, иначе получишь exception.

Вообще, ты не совсем верно используешь `AsyncTask`. У него ведь как раз есть метод для обновления UI - `onPostExecute`. А сейчас фактически у тебя получается, что нет никакого смысла в `JsonTask`. С тем же успехом ты мог бы всё делать прямо в `onCreate`.

Чтобы лучше понять о чём я говорю - попробуй добавить вращающийся `ProgressBar` на время пока загружаются данные. У тебя это не получится при таком подходе, потому что весь интерфейс будет висеть.

**Comment by Nourepide** [comment]
Я об этом читал, тут другая причина
Я еще не знаю как работать с UI из `onPostExecute`, приходят данные и мне нужно сказать `RecyclerCiew.adopter` что-бы он обновился, но как?
На первый взгляд решение очевидное, либо сохранить значение в переменой и уже после тянуть его из класса и обновлять, либо воспользоваться `findViewById`.
В обеих случаях для доступа к ним нужно сделать `AsyncTask` - `inner`,  и всё будет даже работать, activity стартовать и данные обновлятся.
Однако IDEA так не думает, и во всю заявляет что делать этот класс `inner` антипаттерн и ведёт к утечкам памяти, и его следует в таком случае разместить как static. Но в `companion object` не позволяет хранить inner, что впрочем логично и мы теряем доступ к UI

>This AsyncTask class should be static or leaks might occur 
A static field will leak contexts.  Non-static inner classes have an implicit reference to their outer class. If that outer class is for example a Fragment or Activity, then this reference means that the long-running handler/loader/task will hold a reference to the activity which prevents it from getting garbage collected.  Similarly, direct field references to activities and fragments from these longer running instances can cause leaks.  ViewModel classes should never point to Views or non-application Contexts.  Issue id: StaticFieldLeak

**Comment by olegcherr** [comment]
В целом сейчас это пока что неважно. Но если хочешь избавиться от этого предупреждения, можешь просто передавать adapter в JsonTask. Это позволит убрать `inner`.

**Comment by olegcherr** [comment]
Ну а что насчёт `ProgressBar`? Добавь его на время загрузки. Сразу увидишь одну важную проблему, я полагаю :)

**Comment by Nourepide** [comment]
Хорошо, я займусь этим как только завершу свою работу по ДЗ на Java
Думаю это не займет много времени
