### ISSUE TITLE
Заюзать until

### ISSUE THREAD

**Issue by olegcherr** [Nourepide/CryptocurrencyMonitor#5]
https://github.com/Nourepide/CryptocurrencyMonitor/blob/7cf576b6fdd87a6706dfac5f43323c33e7586369/app/src/main/java/com/nourepide/learning/cryptocurrencymonitor/MainActivity.kt#L61

Тип `: Int` указывать необязательно :)

И вообще `arrayLength` я бы удалил, а вместо этого написал бы так:
`for (i in 0 until jsonArray.length()) {`

Т.е. в Котлине есть `until` спецом для таких случаев.

**Comment by Nourepide** [comment]
Спасибо за информацию, запомню
