### ISSUE TITLE
Избавиться от activityContext

### ISSUE THREAD

**Issue by olegcherr** [Nourepide/CryptocurrencyMonitor#7]
https://github.com/Nourepide/CryptocurrencyMonitor/blob/9ce522aba804d7e51edbb5de488841307241c42a/app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainActivity.kt#L93

Каждый View содержит context. Так что ты мог бы просто заюзать `recyclerView.context` вместо того чтобы протаскивать `activityContext`.

**Comment by Nourepide** [comment]
Спасибо за совет
