### ISSUE TITLE
Повторная анимация при смене ориентации

### ISSUE THREAD

**Issue by olegcherr** [Nourepide/CryptocurrencyMonitor#8]
Хорошо что ты добавил анимацию. Она выявила одну важную проблему, незаметную, если у тебя очень быстрый интернет.

Надо разобраться с ней :)

![3](https://user-images.githubusercontent.com/3730074/47300796-708e1700-d62e-11e8-95c2-1e706723a632.gif)

Кстати у эмулятора есть настройки скорости сети. Полезная штука. Хотя она у меня последнее время что-то не работает... Но штука полезная))

![image](https://user-images.githubusercontent.com/3730074/47301076-1c376700-d62f-11e8-9314-d7f6638d556f.png)

**Comment by Nourepide** [comment]
Причина оказывается не в скорости интернета, AppCompatActivity пересоздаёт (onCreate) инстанс каждый раз при повороте экрана
В таком случае получается что заного происходит вся тяжёлая работа по типу загрузки и парсинга при каждом повороте, надо что-то с этим сделать

**Comment by olegcherr** [comment]
> В таком случае получается что заного происходит вся тяжёлая работа по типу загрузки и парсинга при каждом повороте, надо что-то с этим сделать

Ага! Именно на это я тебе и намекаю :) А повторная анимация - это всего лишь симптом, который заметен при медленном интернете.

Ты с английским дружишь? Рекомендую изучить вот эту доку:
https://developer.android.com/guide/components/activities/activity-lifecycle

Чтобы писать надёжные приложения - нужно хорошо понимать жизненный цикл Активити.

**Comment by Nourepide** [comment]
Полностью переработал поведение, теперь загрузка всего (Инициалиация) будет происходит единоразово в отличии от обновления интерфейса в который теперь включёна анимация
